steps:
  - label: ":test_tube: Unit Tests"
    commands: 
      - "scripts/ci/install-helm-env.sh"
      - "scripts/ci/helm-unittest.sh"

  - label: ":database: Schema Validation"
    commands: 
      - "scripts/ci/install-helm-env.sh"
      - "scripts/ci/validate-schema.sh"
